In [ ]:
import pandas as pd
import numpy as np

In [3]:
c_data = pd.read_csv(r"C:\Users\vmadda\OneDrive - hsconline\Desktop\ADE\python\py 1 to 3 assignments\Python_Assignment1\Ele_Store1.csv")

In [24]:
#1) Query the list of columns?
#c_data.dtypes
#c_data.columns
column_list = list(c_data.columns)
print(column_list)

['OrderID', 'OrderDate', 'UnitCost', 'Price', 'OrderQty', 'CostofSales', 'Sales', 'Profit', 'Channel', 'PromotionName', 'ProductName', 'Manufacturer', 'ProductSubCategory', 'ProductCategory', 'Region', 'City', 'Country']

In [25]:
#2) Query the top 5 rows?
c_data.head(5)

,OrderID,OrderDate,UnitCost,Price,OrderQty,CostofSales,Sales,Profit,Channel,PromotionName,ProductName,Manufacturer,ProductSubCategory,ProductCategory,Region,City,Country
0,7077,13-09-2017,76.094968,304.00,9,684.854710,2714.7200,2029.865290,Store,European Spring Promotion,Contoso SLR Camera M143 Grey,"Contoso, Ltd",Digital SLR Cameras,Cameras and camcorders,Europe,Moscow,Russia
1,117,14-09-2017,7.491753,12.99,4,29.967011,50.1414,20.174389,Store,European Spring Promotion,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",MP4&MP3,Audio,Europe,Moscow,Russia
2,7018,15-09-2017,10.122338,159.99,9,91.101039,1395.1128,1304.011761,Store,European Spring Promotion,Contoso DVD 9-Inch Player Portable M300 Silver,"Contoso, Ltd",Movie DVD,"Music, Movies and Audio Books",Europe,Moscow,Russia
3,140,16-09-2017,0.576153,25.69,18,10.370759,462.4200,452.049241,Store,North America Spring Promotion,NT Bluetooth Stereo Headphones E52 Pink,Northwind Traders,Bluetooth Headphones,Audio,North America,Bellevue,United States
4,491,17-09-2017,108.508777,304.00,9,976.578991,2614.4000,1637.821009,Online,Asian Spring Promotion,Contoso SLR Camera M143 Grey,"Contoso, Ltd",Digital SLR Cameras,Cameras and camcorders,Asia,Beijing,China

In [26]:
#3) Query the bottom 5 rows?
c_data.tail(5)

,OrderID,OrderDate,UnitCost,Price,OrderQty,CostofSales,Sales,Profit,Channel,PromotionName,ProductName,Manufacturer,ProductSubCategory,ProductCategory,Region,City,Country
14995,22348,03-10-2058,16.240455,25.0,12,194.885455,300.0,105.114545,Store,Asian Summer Promotion,Contoso USB Cable M250 Blue,"Contoso, Ltd",Cameras & Camcorders Accessories,Cameras and camcorders,Asia,Osaka,Japan
14996,22349,04-10-2058,55.387212,999.0,10,553.872121,9990.0,9436.127879,Reseller,No Discount,WWI Projector 720p DLP56 White,Wide World Importers,Projectors & Screens,Computers,Europe,Paris,France
14997,22350,05-10-2058,363.634986,588.0,13,4727.254816,7408.8,2681.545184,Store,North America Holiday Promotion,"A. Datum SLR Camera 35"" X358 Gold",A. Datum Corporation,Digital SLR Cameras,Cameras and camcorders,North America,Ithaca,United States
14998,22351,06-10-2058,113.237461,279.0,12,1358.849536,3348.0,1989.150464,Online,Asian Summer Promotion,Adventure Works LCD20W M240 Black,Adventure Works,Monitors,Computers,Asia,Beijing,China
14999,22352,07-10-2058,10.936943,15.9,20,218.738862,318.0,99.261138,Store,No Discount,Contoso USB Wave Multi-media Keyboard E280 Black,"Contoso, Ltd",Computers Accessories,Computers,North America,Spring,United States

In [44]:
#4) How many total number of orders placed?
c_data['OrderID'].count()
c_data.shape[0] #or len(c_data)

15000

In [50]:
#5) What are the unique channels present and how many are there?
#c_data['Channel'].
c_data['Channel'].unique()

array(['Store', 'Online', 'Reseller', 'Catalog'], dtype=object)

In [48]:
c_data['Channel'].nunique()

4

In [4]:
#6) How many cities are there?
c_data['City'].nunique()

263

In [5]:
#7) Query the unique Countries and count of the countries?
c_data['Country'].unique()

array(['Russia', 'United States', 'China', 'United Kingdom', 'Canada',
       'Germany', 'Turkmenistan', 'France', 'Australia', 'Iran',
       'Thailand', 'Kyrgyzstan', 'South Korea', 'Pakistan', 'India',
       'Japan', 'Ireland', 'Singapore', 'Armenia', 'Greece', 'Romania',
       'Denmark', 'Italy', 'Malta', 'Portugal', 'Slovenia', 'Syria',
       'Switzerland', 'Taiwan', 'the Netherlands', 'Poland', 'Bhutan',
       'Spain', 'Sweden'], dtype=object)

In [54]:
c_data['Country'].nunique()

34

In [60]:
#8) Query the unique Regions and count of the regions?
c_data['Region'].unique()
c_data['Region'].nunique()

3

In [6]:
#9) Query the total cities count by Country and order it from highest count to lowest count?
c_data['City'].count()

15000

In [10]:

# Group by 'Country' and count the number of cities
city_counts = c_data.groupby('Country')['City'].count()

# Sort the result from highest to lowest
sorted_city_counts = city_counts.sort_values(ascending=False)

# Display the result
print(sorted_city_counts)

Country
United States      8510
China              1673
Germany            1118
France              781
United Kingdom      477
Canada              359
Japan               298
Russia              166
India               152
Australia           149
Turkmenistan        119
Italy               111
Pakistan             93
Iran                 89
Syria                86
Thailand             82
South Korea          72
Taiwan               50
Singapore            49
Bhutan               48
Kyrgyzstan           46
Armenia              44
Denmark              42
Malta                41
Romania              39
the Netherlands      38
Portugal             38
Ireland              37
Poland               37
Switzerland          35
Slovenia             34
Spain                32
Sweden               30
Greece               25
Name: City, dtype: int64

In [ ]:
#10) How many products are there? Display count of products
c_data['ProductName'].count()

In [15]:
c_data['ProductName'].value_counts()

ProductName
WWI Desktop PC1.80 E1802 White                              25
Litware Home Theater System 5.1 Channel M515 Brown          24
Contoso 3 Handset Cordless Phone System  E30 Black          22
Contoso Optical Wheel OEM PS/2 Mouse E60 Silver             22
Contoso Touch Screen Phones SAW/On-wall M806 Black          21
                                                            ..
Contoso DVD Player M140 Gold                                 1
Litware Home Theater System 7.1 Channel X711 Silver          1
SV 500GB USB 2.0 Portable External Hard Drive X405 Black     1
A. Datum Ultra Compact Digital Camera M190 Grey              1
Contoso 16GB Mp5 Player M1600 Red                            1
Name: count, Length: 1638, dtype: int64

In [23]:
#11) Query the total sales and total profit?
sales = c_data['Sales'].sum()

profit = c_data['Profit'].sum()

In [26]:
print("Total Sales",round(sales,2))
print("Total Profit",round(profit,2))

Total Sales 55391759.79
Total Profit 31587437.29

In [31]:
#12) Query the total sales by region and country?
#c_data.head(5)
total_sales = c_data.groupby(['Region','Country'])['Sales'].sum().reset_index()
total_sales.rename(columns={'Sales': 'Total_Sales'},inplace=True)
print(total_sales)

           Region          Country   Total_Sales
0            Asia          Armenia  1.729347e+05
1            Asia        Australia  6.326425e+05
2            Asia           Bhutan  1.612916e+05
3            Asia            China  7.557974e+06
4            Asia            India  5.984046e+05
5            Asia             Iran  3.679533e+05
6            Asia            Japan  9.583344e+05
7            Asia       Kyrgyzstan  1.271148e+05
8            Asia         Pakistan  2.965706e+05
9            Asia        Singapore  9.922349e+04
10           Asia      South Korea  2.506013e+05
11           Asia            Syria  3.296714e+05
12           Asia           Taiwan  1.890095e+05
13           Asia         Thailand  2.582489e+05
14           Asia     Turkmenistan  4.123702e+05
15         Europe          Denmark  7.914523e+04
16         Europe           France  2.628401e+06
17         Europe          Germany  4.314956e+06
18         Europe           Greece  6.852796e+04
19         Europe          Ireland  9.212368e+04
20         Europe            Italy  3.168811e+05
21         Europe            Malta  1.122952e+05
22         Europe           Poland  8.782953e+04
23         Europe         Portugal  1.263816e+05
24         Europe          Romania  1.022789e+05
25         Europe           Russia  4.342403e+05
26         Europe         Slovenia  7.988141e+04
27         Europe            Spain  1.434332e+05
28         Europe           Sweden  7.810665e+04
29         Europe      Switzerland  9.936224e+04
30         Europe   United Kingdom  1.324267e+06
31         Europe  the Netherlands  1.077465e+05
32  North America           Canada  1.148316e+06
33  North America    United States  3.163524e+07

In [36]:
#13) Query the total order qty by promotion name?
#c_data.head(5)
total_order_qty=c_data.groupby('PromotionName')['OrderQty'].sum().reset_index()
total_order_qty.rename(columns={'OrderQty':'Total_qty'},inplace=True)
print(total_order_qty)

                            PromotionName  Total_qty
0                 Asian Holiday Promotion      17004
1                  Asian Spring Promotion      10980
2                  Asian Summer Promotion       9768
3       European Back-to-Scholl Promotion       7363
4              European Holiday Promotion      12328
5               European Spring Promotion      13205
6                             No Discount      80062
7  North America Back-to-School Promotion      39393
8         North America Holiday Promotion      30392
9          North America Spring Promotion      30631

In [45]:
#14) Query the top 7 countries with sales from highest to lowest order?
sales=c_data.groupby('Country')['Sales'].sum().reset_index()
sales.rename(columns={'Sales':'Total Sales'},inplace=True)
total_sales=sales.sort_values(by='Total Sales',ascending=False)
top_7=total_sales.head(7)
print(top_7)

           Country   Total Sales
32   United States  3.163524e+07
4            China  7.557974e+06
7          Germany  4.314956e+06
6           France  2.628401e+06
31  United Kingdom  1.324267e+06
3           Canada  1.148316e+06
13           Japan  9.583344e+05

In [51]:
#15) How much the total sales happened in Asia region?
asia_sales=c_data[c_data['Region']=='Asia']['Sales'].sum()
print(asia_sales)

12412345.056499999

In [48]:
# Filter the dataset for Asia region and sum the Sales
asia_sales = c_data[c_data['Region'] == 'Asia']['Sales'].sum()

# Optional: Round and format the result
print("Total Sales in Asia Region:", round(asia_sales, 2))

Total Sales in Asia Region: 12412345.06

In [53]:
#16) How much total sales happened in Asia region and India?
total_sales = c_data[(c_data['Region'] == 'Asia') & (c_data['Country'] == 'India')]['Sales'].sum()
print("Total Sales in Asia Region and India:", round(total_sales, 2))

Total Sales in Asia Region and India: 598404.61

In [63]:
#17) How much profit got in Europe region and Denmark country?
total_profit = c_data[(c_data['Region']=='Europe') & (c_data['Country']=='Denmark')]['Profit'].sum()
print("Total profit in Europe region and Denmark:", round(total_profit,2))

Total profit in Europe region and Denmark: 45194.07

In [68]:
#18) Query the total order qty by Manufacturer and Product Name?
total_order_qty = c_data.groupby(['Manufacturer', 'ProductName'])['OrderQty'].sum().reset_index()
total_order_qty.rename(columns={'OrderQty':'Total_Qty'},inplace=True)
print(total_order_qty)

              Manufacturer                                        ProductName  \
0     A. Datum Corporation        A. Datum Advanced Digital Camera M300 Azure
1     A. Datum Corporation        A. Datum Advanced Digital Camera M300 Black
2     A. Datum Corporation        A. Datum Advanced Digital Camera M300 Green
3     A. Datum Corporation         A. Datum Advanced Digital Camera M300 Grey
4     A. Datum Corporation       A. Datum Advanced Digital Camera M300 Orange
...                    ...                                                ...
1633  Wide World Importers  WWI Wireless Transmitter and Bluetooth Headpho...
1634  Wide World Importers  WWI Wireless Transmitter and Bluetooth Headpho...
1635  Wide World Importers  WWI Wireless Transmitter and Bluetooth Headpho...
1636  Wide World Importers  WWI Wireless Transmitter and Bluetooth Headpho...
1637  Wide World Importers  WWI Wireless Transmitter and Bluetooth Headpho...

      Total_Qty
0            77
1           142
2            96
3           207
4           115
...         ...
1633         45
1634         65
1635         60
1636         60
1637         48

[1638 rows x 3 columns]

In [75]:
#19) Query the top 7 products with orderqty and sales and show it descending order based on total orderqty?
top_7_products = c_data.groupby('ProductName')[['OrderQty', 'Sales']].sum().reset_index()

top_7_products = top_7_products.sort_values(by='OrderQty', ascending=False).head(7)

print(top_7_products)

                                           ProductName  OrderQty       Sales
531                Contoso In-Line Coupler E180 Silver      6780  22696.2500
952    Headphone Adapter for Contoso Phone E130 Silver      4680  46730.9223
664  Contoso Rubberized Snap-On Cover Hard Case Cel...      4580  21700.9050
532                 Contoso In-Line Coupler E180 White      4060  13588.4375
661     Contoso Rubberized Skin BlackBerry E100 Silver      3560  53319.8797
257  Cigarette Lighter Adapter for Contoso Phones E...      3520  87912.3210
663  Contoso Rubberized Snap-On Cover Hard Case Cel...      3280  15534.4020

In [79]:
#20) Query the total order quantity greater than 10000 by city?
city_order_qty = c_data.groupby('City')['OrderQty'].sum().reset_index()

high_order_cities = city_order_qty[city_order_qty['OrderQty'] > 10000]

print(high_order_cities)

              City  OrderQty
25         Beijing     30547
27          Berlin     13841
30        Bethesda     20498
170  North Harford     24806
210        Seattle     12174

In [82]:
#21) Query the total sales less than 1000 by product, display it in ascending order?
product_total_sales= c_data.groupby('ProductName')['Sales'].sum().reset_index()
less_sales_products= product_total_sales[product_total_sales['Sales']<1000]
less_sales_products_sortby = less_sales_products.sort_values(by='Sales', ascending=True)

print(less_sales_products_sortby)

                                            ProductName     Sales
1353                        SV USB Data Cable E600 Grey   45.6950
1358               SV USB Sync Charge Cable E700 Silver   64.0780
1354                        SV USB Data Cable E600 Pink  100.4340
1352                       SV USB Data Cable E600 Black  124.2600
1357                 SV USB Sync Charge Cable E700 Blue  142.6830
1356                SV USB Sync Charge Cable E700 Black  160.3940
1359                SV USB Sync Charge Cable E700 White  170.7420
1355                      SV USB Data Cable E600 Silver  202.8060
622   Contoso Primary Extended Capacity Battery Pack...  203.4000
761     Contoso USB Wave Multi-Media Keyboard M901 Gold  259.0000
421   Contoso Digital Cordless Expansion Handset Pho...  293.6110
783   Contoso Wireless Notebook Optical Mouse M35 White  299.5000
422   Contoso Digital Cordless Expansion Handset Pho...  329.9000
655         Contoso Reserve Pen - Tablet Pen E200 Black  332.2100
766     Contoso Ultraportable Neoprene Sleeve E30 Green  335.4000
612   Contoso Phone with Memory Dialing-2 lines E90 ...  382.4000
781   Contoso Wireless Notebook Optical Mouse M35 Or...  383.3600
285   Contoso 4-Line Corded Cordless Telephone M203 ...  395.8800
559                 Contoso Lens Cap Keeper E314 Silver  415.6100
399                       Contoso DVD Player M100 Black  504.3615
463            Contoso General Carrying Case E304 White  511.7440
418   Contoso Digital Cameras Lightweight Tripod E31...  521.3000
411      Contoso Digital Camera Accessory kit M200 Blue  525.8000
435        Contoso Education Supplies Bundle E200 Black  532.5750
721                     Contoso Smart Battery M901 Blue  547.4000
564                          Contoso Lens cap E80 White  599.0000
402                        Contoso DVD Player M140 Gold  609.9000
757                 Contoso USB Optical Mouse E200 Gold  669.6000
763     Contoso USB Wave Multi-media Keyboard E280 Blue  670.9800
720                    Contoso Smart Battery M901 Black  672.1750
658         Contoso Reserve Pen - Tablet Pen E200 White  678.3200
319   Contoso ADSL Modem Splitter/Filter X 1 E100 White  680.2000
1330                            SV DVD Player M130 Grey  713.8810
1312            SV DVD 58 DVD Storage Binder M55 Silver  738.9480
560                  Contoso Lens Cap Keeper E314 White  749.2795
784   Contoso Wireless Notebook Optical Mouse X205 O...  766.7050
562                          Contoso Lens cap E80 Black  778.7000
1303            SV DVD 38 DVD Storage Binder E25 Silver  816.1830
550            Contoso Laptop Starter Bundle M200 White  837.0450
466      Contoso General Soft Carrying Case E318 Silver  867.1715
549             Contoso Laptop Starter Bundle M200 Grey  891.0000
548            Contoso Laptop Starter Bundle M200 Black  898.4250
364   Contoso Cyber Shot Digital Cameras Adapter E30...  901.7745
628           Contoso Private Branch Exchange M88 White  912.1735
409        Contoso Desktop Alternative Bundle E200 Grey  915.4000
465        Contoso General Soft Carrying Case E318 Blue  929.3800
782   Contoso Wireless Notebook Optical Mouse M35 Si...  949.4150
611   Contoso Phone with Memory Dialing-2 lines E90 ...  960.0000
434      Contoso Education Essentials Bundle M300 White  994.2700
657          Contoso Reserve Pen - Tablet Pen E200 Grey  996.6300

In [85]:
#22) Query the total profit greater than 200000 by product, display it in descending order?

high_profit_products = c_data.groupby('ProductName')['Profit'].sum().reset_index()
total_profit_products= high_profit_products[high_profit_products['Profit']>200000]
total_profit_products_sort=total_profit_products.sort_values(by='Profit',ascending =False)
print(total_profit_products_sort)

                                 ProductName         Profit
631       Contoso Projector 1080p X980 White  320513.293550
1157   Proseware Projector 1080p LCD86 White  315379.915450
629       Contoso Projector 1080p X980 Black  252654.597032
1155   Proseware Projector 1080p LCD86 Black  232556.514538
1153  Proseware Projector 1080p DLP86 Silver  228823.614999
1152   Proseware Projector 1080p DLP86 Black  208705.101207
                                            ProductName     Sales
1353                        SV USB Data Cable E600 Grey   45.6950
1358               SV USB Sync Charge Cable E700 Silver   64.0780
1354                        SV USB Data Cable E600 Pink  100.4340
1352                       SV USB Data Cable E600 Black  124.2600
1357                 SV USB Sync Charge Cable E700 Blue  142.6830
1356                SV USB Sync Charge Cable E700 Black  160.3940
1359                SV USB Sync Charge Cable E700 White  170.7420
1355                      SV USB Data Cable E600 Silver  202.8060
622   Contoso Primary Extended Capacity Battery Pack...  203.4000
761     Contoso USB Wave Multi-Media Keyboard M901 Gold  259.0000
421   Contoso Digital Cordless Expansion Handset Pho...  293.6110
783   Contoso Wireless Notebook Optical Mouse M35 White  299.5000
422   Contoso Digital Cordless Expansion Handset Pho...  329.9000
655         Contoso Reserve Pen - Tablet Pen E200 Black  332.2100
766     Contoso Ultraportable Neoprene Sleeve E30 Green  335.4000
612   Contoso Phone with Memory Dialing-2 lines E90 ...  382.4000
781   Contoso Wireless Notebook Optical Mouse M35 Or...  383.3600
285   Contoso 4-Line Corded Cordless Telephone M203 ...  395.8800
559                 Contoso Lens Cap Keeper E314 Silver  415.6100
399                       Contoso DVD Player M100 Black  504.3615
463            Contoso General Carrying Case E304 White  511.7440
418   Contoso Digital Cameras Lightweight Tripod E31...  521.3000
411      Contoso Digital Camera Accessory kit M200 Blue  525.8000
435        Contoso Education Supplies Bundle E200 Black  532.5750
721                     Contoso Smart Battery M901 Blue  547.4000
564                          Contoso Lens cap E80 White  599.0000
402                        Contoso DVD Player M140 Gold  609.9000
757                 Contoso USB Optical Mouse E200 Gold  669.6000
763     Contoso USB Wave Multi-media Keyboard E280 Blue  670.9800
720                    Contoso Smart Battery M901 Black  672.1750
658         Contoso Reserve Pen - Tablet Pen E200 White  678.3200
319   Contoso ADSL Modem Splitter/Filter X 1 E100 White  680.2000
1330                            SV DVD Player M130 Grey  713.8810
1312            SV DVD 58 DVD Storage Binder M55 Silver  738.9480
560                  Contoso Lens Cap Keeper E314 White  749.2795
784   Contoso Wireless Notebook Optical Mouse X205 O...  766.7050
562                          Contoso Lens cap E80 Black  778.7000
1303            SV DVD 38 DVD Storage Binder E25 Silver  816.1830
550            Contoso Laptop Starter Bundle M200 White  837.0450
466      Contoso General Soft Carrying Case E318 Silver  867.1715
549             Contoso Laptop Starter Bundle M200 Grey  891.0000
548            Contoso Laptop Starter Bundle M200 Black  898.4250
364   Contoso Cyber Shot Digital Cameras Adapter E30...  901.7745
628           Contoso Private Branch Exchange M88 White  912.1735
409        Contoso Desktop Alternative Bundle E200 Grey  915.4000
465        Contoso General Soft Carrying Case E318 Blue  929.3800
782   Contoso Wireless Notebook Optical Mouse M35 Si...  949.4150
611   Contoso Phone with Memory Dialing-2 lines E90 ...  960.0000
434      Contoso Education Essentials Bundle M300 White  994.2700
657          Contoso Reserve Pen - Tablet Pen E200 Grey  996.6300

In [92]:
#23) How much total sales happened in China and Beijing?
total_sales= c_data[(c_data['Country']=='China')& (c_data['City']=='Beijing')]['Sales'].sum()
print(total_sales)

6596953.0955
Total profit in Europe region and Denmark: 45194.07

In [93]:
#24) How much total sales happened in Asian Holiday Promotion?

total_sales= c_data[c_data['PromotionName']=='Asian Holiday Promotion']['Sales'].sum()
print(total_sales)

3615193.9905000003

In [96]:
#25) How much total profit value by Contoso, Ltd Manufacturer?
total_profit= c_data[c_data['Manufacturer']=='Contoso, Ltd']['Profit'].sum()
print(round(total_profit,2))

5670159.66

In [99]:
#26) Query the total sales and total order qty by product category and order it by Orderqty from highest to lowest?
product_sales_qty=c_data.groupby('ProductCategory')[['Sales','OrderQty']].sum().reset_index()
product_sales_qty_sort= product_sales_qty.sort_values(by='OrderQty',ascending=False)
print(product_sales_qty_sort)

                 ProductCategory         Sales  OrderQty
2                    Cell phones  5.841156e+06     96074
3                      Computers  2.130697e+07     69425
1        Cameras and camcorders   1.704893e+07     43893
5                   TV and Video  9.107839e+06     22714
4  Music, Movies and Audio Books  1.057480e+06      9953
0                          Audio  1.029381e+06      9067

In [101]:
#27) Query the total sales value in between 1057 and 26700 by Region?
total_sales=c_data.groupby('Region')['Sales'].sum()
#sort=total_sales['1057' 
print(total_sales)

Region
Asia             1.241235e+07
Europe           1.019586e+07
North America    3.278356e+07
Name: Sales, dtype: float64

In [107]:
#28) How many orders placed in Pittsfield city?
orders = c_data[c_data['City']=='Pittsfield'].shape[0]
print(orders)

31

In [110]:
#29) Query the total sales and total profit by region, country and city?
sales_profit=c_data.groupby(['Region','Country','City'])[['Sales','Profit']].sum().reset_index()
print(sales_profit)

            Region        Country         City         Sales        Profit
0             Asia        Armenia      Yerevan  1.729347e+05  1.119702e+05
1             Asia      Australia     Canberra  2.112396e+05  9.384047e+04
2             Asia      Australia       Sydney  4.214029e+05  2.503940e+05
3             Asia         Bhutan      Thimphu  1.612916e+05  8.817516e+04
4             Asia          China      Beijing  6.596953e+06  3.810007e+06
..             ...            ...          ...           ...           ...
258  North America  United States     Waukesha  1.953965e+05  9.556164e+04
259  North America  United States  Wheat Ridge  1.295698e+05  5.794578e+04
260  North America  United States   Winchester  9.426428e+04  5.261520e+04
261  North America  United States    Worcester  1.839504e+05  1.087016e+05
262  North America  United States       Yakima  1.008435e+05  7.079848e+04

[263 rows x 5 columns]

In [113]:
#30) Query the total unit cost and total price by productcategory, productsubcategory and Manufacturer?
#c_data.head(5)
unit_cost_price= c_data.groupby(['ProductCategory','ProductSubCategory','Manufacturer'])[['UnitCost','UnitCost']].sum().reset_index()
print(unit_cost_price)

                  ProductCategory                ProductSubCategory  \
0                           Audio              Bluetooth Headphones
1                           Audio              Bluetooth Headphones
2                           Audio                           MP4&MP3
3                           Audio                     Recording Pen
4         Cameras and camcorders                         Camcorders
5         Cameras and camcorders   Cameras & Camcorders Accessories
6         Cameras and camcorders                    Digital Cameras
7         Cameras and camcorders                Digital SLR Cameras
8         Cameras and camcorders                Digital SLR Cameras
9         Cameras and camcorders                Digital SLR Cameras
10                    Cell phones           Cell phones Accessories
11                    Cell phones              Home & Office Phones
12                    Cell phones              Smart phones & PDAs
13                    Cell phones              Touch Screen Phones
14                    Cell phones              Touch Screen Phones
15                      Computers             Computers Accessories
16                      Computers             Computers Accessories
17                      Computers                          Desktops
18                      Computers                          Desktops
19                      Computers                           Laptops
20                      Computers                           Laptops
21                      Computers                           Laptops
22                      Computers                           Laptops
23                      Computers                          Monitors
24                      Computers                          Monitors
25                      Computers                          Monitors
26                      Computers          Printers, Scanners & Fax
27                      Computers              Projectors & Screens
28                      Computers              Projectors & Screens
29                      Computers              Projectors & Screens
30  Music, Movies and Audio Books                         Movie DVD
31  Music, Movies and Audio Books                         Movie DVD
32                   TV and Video                         Car Video
33                   TV and Video               Home Theater System
34                   TV and Video               Home Theater System
35                   TV and Video                       Televisions
36                   TV and Video                         VCD & DVD

            Manufacturer       UnitCost       UnitCost
0      Northwind Traders    4694.140924    4694.140924
1   Wide World Importers    5348.553816    5348.553816
2           Contoso, Ltd   15180.676953   15180.676953
3   Wide World Importers   10165.599158   10165.599158
4         Fabrikam, Inc.  286756.395516  286756.395516
5           Contoso, Ltd   12221.056068   12221.056068
6   A. Datum Corporation   88363.414849   88363.414849
7   A. Datum Corporation   55606.839775   55606.839775
8           Contoso, Ltd   61069.829295   61069.829295
9         Fabrikam, Inc.   64966.210095   64966.210095
10          Contoso, Ltd    1526.510851    1526.510851
11          Contoso, Ltd   12044.658547   12044.658547
12     The Phone Company  103969.796452  103969.796452
13          Contoso, Ltd   12851.720868   12851.720868
14     The Phone Company   55433.985480   55433.985480
15          Contoso, Ltd   16153.021031   16153.021031
16      Southridge Video   12789.845684   12789.845684
17       Adventure Works   43576.939570   43576.939570
18  Wide World Importers   31821.889351   31821.889351
19       Adventure Works   93609.664408   93609.664408
20        Fabrikam, Inc.   52102.113425   52102.113425
21       Proseware, Inc.   26831.171937   26831.171937
22  Wide World Importers   45528.259167   45528.259167
23       Adventure Works   23132.559566   23132.559566
24       Proseware, Inc.   17530.704507   17530.704507
25  Wide World Importers   22386.928271   22386.928271
26       Proseware, Inc.   65123.253204   65123.253204
27          Contoso, Ltd   78241.936027   78241.936027
28       Proseware, Inc.   99812.740227   99812.740227
29  Wide World Importers   62842.407007   62842.407007
30          Contoso, Ltd   16690.866047   16690.866047
31      Southridge Video   17559.035965   17559.035965
32      Southridge Video   84685.148227   84685.148227
33          Contoso, Ltd   97944.784475   97944.784475
34         Litware, Inc.   87195.387626   87195.387626
35       Adventure Works   71821.432011   71821.432011
36      Southridge Video    8797.508772    8797.508772